redis:
  image: redis
db:
  image: postgres
nginx:
  image: nginx
  links:
    - uwsgi
  volumes:
    - .:/code
    - ./devscripts/docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - 9000:80
uwsgi:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: 'podiobooks.settings_docker_compose'
  command: uwsgi --yaml=devscripts/docker-compose/uwsgi-compose.yml
  volumes:
    - .:/code
  ports:
    - 7000
  links:
    - db
    - redis
varnish:
  image: million12/varnish
  ports:
    - 9500:80
  links:
    - nginx
  volumes:
    - ./devscripts/docker-compose/varnish.vcl:/etc/varnish/default.vcl:ro