redis:
  container_name: podiobooks_redis
  dns:
    - 127.0.0.1
  image: redis
db:
  container_name: podiobooks_postgres
  dns:
    - 127.0.0.1
  image: postgres
nginx:
  container_name: podiobooks_nginx
  dns:
    - 127.0.0.1
    - 8.8.8.8
  image: nginx
  ports:
    - 8080
  volumes:
    - .:/code
    - ./devscripts/docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
uwsgi:
  build: .
  command: uwsgi --yaml=devscripts/docker-compose/uwsgi-compose.yml
  container_name: podiobooks_uwsgi
  dns:
    - 127.0.0.1
    - 8.8.8.8
  environment:
    DJANGO_SETTINGS_MODULE: 'podiobooks.settings_docker_compose'
  ports:
    - 7000
  volumes:
    - .:/code
    - ./devscripts/docker-compose/varnish_secret:/etc/varnish/secret:ro
varnish:
  container_name: podiobooks_varnish
  environment:
    VARNISHD_PARAMS: -a :8000 -T :6082 -S /etc/varnish/secret
  dns:
    - 127.0.0.1
    - 8.8.8.8
  image: million12/varnish
  ports:
    - 6082 # Management Port
    - 8000:8000
  volumes:
    - ./devscripts/docker-compose/varnish.vcl:/etc/varnish/default.vcl:ro
    - ./devscripts/docker-compose/varnish_secret:/etc/varnish/secret:ro
  volumes_from:
    - nginx # Forces varnish to load after nginx
    - uwsgi  # Forces varnish to load after uwsgi